name: NabtoEdgeClientHello
options:
  bundleIdPrefix: com.nabto.edge
  deploymentTarget:
    iOS: "14.0"
  developmentLanguage: en
  createIntermediateGroups: true

packages:
  NabtoEdgeClient:
    path: ../

targets:
  NabtoEdgeClientHello:
    type: application
    platform: iOS
    sources:
      - NabtoEdgeClientHello
    dependencies:
      - package: NabtoEdgeClient
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nabto.edge.NabtoEdgeClientHello
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: NabtoEdgeClientHello/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
