# changes seems to take forever to synchronize to pods 1.8+ CDN, use old
# github approach for immediate retrieval (but slower once synched, so only
# relevant during development)
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'NabtoEdgeClient' do
  pod 'NabtoEdgeClientApiFW', '5.12.1'
end

target 'HostForTests' do
end

target 'NabtoEdgeClientTests' do
#  pod 'NabtoClient'
end
